--- #YAML:1.0
build_requires: {}
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.14
license: perl
name: Crypt-SKey
recommends:
  Digest::MD4: 1
  Digest::MD5: 2.16
  Term::ReadKey: 2.14
requires: {}
version: 0.05
