--- #YAML:1.0
name: Crypt-SKey
version: 0.06
license: perl
distribution_type: module
requires: {}
recommends:
  Digest::MD4: 1
  Digest::MD5: 2.16
  Term::ReadKey: 2.14
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.15
